from dataclasses import dataclass, asdict
from typing import List


# --------------------------------------------------
# Retrieval Models
# --------------------------------------------------

@dataclass
class RetrievedChunk:
    """
    Represents a document chunk retrieved from
    the vector database.
    """

    id: str

    document_id: str

    text: str

    source: str

    raw: dict

    score: float


# --------------------------------------------------
# Workflow Metadata
# --------------------------------------------------

@dataclass
class WorkflowMetadata:
    """
    Structured workflow metadata extracted from
    retrieved workflow documentation.

    These fields are deterministic and should NOT
    be generated by the LLM.
    """

    current_stage: str = "Not Available"

    current_approver: str = "Not Available"

    next_step: str = "Not Available"

    sla: str = "Not Available"


# --------------------------------------------------
# Workflow Response
# --------------------------------------------------

@dataclass
class WorkflowResponse:
    """
    Final response returned by WorkflowService.
    """

    summary: str

    metadata: WorkflowMetadata

    confidence: float

    sources: List[str]

    def to_dict(self):

        return {
            "summary": self.summary,

            "current_stage":
                self.metadata.current_stage,

            "current_approver":
                self.metadata.current_approver,

            "next_step":
                self.metadata.next_step,

            "sla":
                self.metadata.sla,

            "confidence":
                self.confidence,

            "sources":
                self.sources
        }